In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
bike_Pedestrain_crash_df = pd.read_csv(R"C:\Users\umar_\OneDrive\Desktop\Capstone Project\Bikeride data.csv")
bike_Pedestrain_crash_df.head()

X          Y  OBJECTID_1 AmbulanceR BikeAge BikeAgeGrp  \
0 -80.878436  35.231039        3155         No       7     06-Oct   
1 -77.894637  34.079405        4236        Yes      41      40-49   
2 -78.973815  35.975543        5121        Yes      16      16-19   
3 -80.848932  36.239883        5610         No      17      16-19   
4 -79.188513  34.684359        5631         No      46      40-49   

                        BikeAlcDrg BikeAlcFlg         BikeDir  \
0  Yes-Drugs, impairment suspected         No    With Traffic   
1  Yes-Drugs, impairment suspected         No  Facing Traffic   
2  Yes-Drugs, impairment suspected         No    With Traffic   
3  Yes-Drugs, impairment suspected         No    With Traffic   
4  Yes-Drugs, impairment suspected         No  Facing Traffic   

                    BikeInjury  ... RdDefects           RdFeature  \
0                 O: No Injury  ...      None             Missing   
1  A: Suspected Serious Injury  ...      None    Driveway, Public   
2           C: Possible Injury  ...      None  No Special Feature   
3           C: Possible Injury  ...      None      T-Intersection   
4           C: Possible Injury  ...      None  No Special Feature   

        RdSurface     Region RuralUrban    SpeedLimit          TraffCntrl  \
0  Smooth Asphalt   Piedmont      Urban  30 - 35  MPH  No Control Present   
1  Coarse Asphalt    Coastal      Rural  40 - 45  MPH  No Control Present   
2  Smooth Asphalt   Piedmont      Urban  30 - 35  MPH  No Control Present   
3  Smooth Asphalt  Mountains      Rural  30 - 35  MPH  No Control Present   
4  Smooth Asphalt    Coastal      Rural  30 - 35  MPH  No Control Present   

  Weather  Workzone  OBJECTID  
0  Cloudy        No      3155  
1   Clear        No      4236  
2   Clear        No      5121  
3    Rain        No      5610  
4   Clear        No      5631  

[5 rows x 62 columns]

In [3]:
bike_Pedestrain_crash_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12173 entries, 0 to 12172
Data columns (total 62 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   X           12173 non-null  float64
 1   Y           12173 non-null  float64
 2   OBJECTID_1  12173 non-null  int64  
 3   AmbulanceR  12173 non-null  object 
 4   BikeAge     12173 non-null  object 
 5   BikeAgeGrp  12173 non-null  object 
 6   BikeAlcDrg  12173 non-null  object 
 7   BikeAlcFlg  12173 non-null  object 
 8   BikeDir     12173 non-null  object 
 9   BikeInjury  12173 non-null  object 
 10  BikePos     12173 non-null  object 
 11  BikeRace    12173 non-null  object 
 12  BikeSex     12173 non-null  object 
 13  City        12173 non-null  object 
 14  County      12173 non-null  object 
 15  CrashAlcoh  12173 non-null  object 
 16  CrashDay    12173 non-null  object 
 17  CrashGrp    12173 non-null  object 
 18  CrashHour   12173 non-null  int64  
 19  CrashID     12173 non-nul

In [4]:
#Dropping unknown rows from Bike age group

bike_Pedestrain_crash_df.drop(bike_Pedestrain_crash_df[bike_Pedestrain_crash_df['BikeAgeGrp'] == 'Unknown'].index, inplace = True)

In [5]:
bike_Pedestrain_crash_df.columns

Index(['X', 'Y', 'OBJECTID_1', 'AmbulanceR', 'BikeAge', 'BikeAgeGrp',
       'BikeAlcDrg', 'BikeAlcFlg', 'BikeDir', 'BikeInjury', 'BikePos',
       'BikeRace', 'BikeSex', 'City', 'County', 'CrashAlcoh', 'CrashDay',
       'CrashGrp', 'CrashHour', 'CrashID', 'CrashLoc', 'CrashMonth',
       'CrashSevr', 'CrashType', 'CrashYear', 'Developmen', 'DrvrAge',
       'DrvrAgeGrp', 'DrvrAlcDrg', 'DrvrAlcFlg', 'DrvrInjury', 'DrvrRace',
       'DrvrSex', 'DrvrVehTyp', 'HitRun', 'Latitude', 'LightCond', 'Locality',
       'Longitude', 'NumBicsAin', 'NumBicsBin', 'NumBicsCin', 'NumBicsKil',
       'NumBicsNoi', 'NumBicsTot', 'NumBicsUin', 'NumLanes', 'NumUnits',
       'RdCharacte', 'RdClass', 'RdConditio', 'RdConfig', 'RdDefects',
       'RdFeature', 'RdSurface', 'Region', 'RuralUrban', 'SpeedLimit',
       'TraffCntrl', 'Weather', 'Workzone', 'OBJECTID'],
      dtype='object')

In [36]:
# drop unneccasary columns
bike_Pedestrain_crash_df = bike_Pedestrain_crash_df.drop(['X', "Y","OBJECTID_1","BikeAgeGrp","BikeAlcFlg","CrashGrp","CrashID","NumBicsAin","NumBicsBin","NumBicsCin","NumBicsKil","NumBicsNoi","NumBicsTot","NumBicsUin","RuralUrban"], axis=1)

bike_Pedestrain_crash_df.head()

KeyError: "['X' 'Y' 'OBJECTID_1' 'BikeAgeGrp' 'BikeAlcFlg' 'CrashGrp' 'CrashID'\n 'NumBicsAin' 'NumBicsBin' 'NumBicsCin' 'NumBicsKil' 'NumBicsNoi'\n 'NumBicsTot' 'NumBicsUin' 'RuralUrban'] not found in axis"

In [37]:
bike_Pedestrain_crash_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11948 entries, 0 to 12172
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   AmbulanceR  11948 non-null  object 
 1   BikeAge     11948 non-null  object 
 2   BikeAlcDrg  11948 non-null  object 
 3   BikeDir     11948 non-null  object 
 4   BikeInjury  11948 non-null  object 
 5   BikePos     11948 non-null  object 
 6   BikeRace    11948 non-null  object 
 7   BikeSex     11948 non-null  object 
 8   City        11948 non-null  object 
 9   County      11948 non-null  object 
 10  CrashAlcoh  11948 non-null  object 
 11  CrashDay    11948 non-null  object 
 12  CrashHour   11948 non-null  int64  
 13  CrashLoc    11948 non-null  object 
 14  CrashMonth  11948 non-null  object 
 15  CrashSevr   11948 non-null  object 
 16  CrashType   11948 non-null  object 
 17  CrashYear   11948 non-null  int64  
 18  Developmen  11948 non-null  object 
 19  DrvrAge     11948 non-nul

In [38]:
bike_Pedestrain_crash_df.head()




AmbulanceR BikeAge                       BikeAlcDrg         BikeDir  \
0         No       7  Yes-Drugs, impairment suspected    With Traffic   
1        Yes      41  Yes-Drugs, impairment suspected  Facing Traffic   
2        Yes      16  Yes-Drugs, impairment suspected    With Traffic   
3         No      17  Yes-Drugs, impairment suspected    With Traffic   
4         No      46  Yes-Drugs, impairment suspected  Facing Traffic   

                    BikeInjury      BikePos         BikeRace BikeSex  \
0                 O: No Injury  Travel Lane            Black    Male   
1  A: Suspected Serious Injury  Travel Lane            White  Female   
2           C: Possible Injury  Travel Lane            White    Male   
3           C: Possible Injury  Travel Lane            White    Male   
4           C: Possible Injury  Travel Lane  Native American    Male   

                 City       County  ... RdConditio  \
0           Charlotte  Mecklenburg  ...        Dry   
1  None - Rural Crash  New Hanover  ...        Dry   
2              Durham       Durham  ...        Dry   
3          Jonesville       Yadkin  ...        Wet   
4            Pembroke      Robeson  ...        Dry   

                               RdConfig  RdDefects           RdFeature  \
0                  Two-Way, Not Divided       None             Missing   
1  Two-Way, Divided, Unprotected Median       None    Driveway, Public   
2                  One-Way, Not Divided       None  No Special Feature   
3                  Two-Way, Not Divided       None      T-Intersection   
4  Two-Way, Divided, Unprotected Median       None  No Special Feature   

        RdSurface     Region    SpeedLimit          TraffCntrl Weather  \
0  Smooth Asphalt   Piedmont  30 - 35  MPH  No Control Present  Cloudy   
1  Coarse Asphalt    Coastal  40 - 45  MPH  No Control Present   Clear   
2  Smooth Asphalt   Piedmont  30 - 35  MPH  No Control Present   Clear   
3  Smooth Asphalt  Mountains  30 - 35  MPH  No Control Present    Rain   
4  Smooth Asphalt    Coastal  30 - 35  MPH  No Control Present   Clear   

  Workzone  
0       No  
1       No  
2       No  
3       No  
4       No  

[5 rows x 45 columns]

In [8]:
# No. of Accidents by Cities
city_df = bike_Pedestrain_crash_df.groupby("City")["City"].count().sort_values(ascending=False)
city_df.head(10)


City
None - Rural Crash    2549
Charlotte             1389
Raleigh               1075
Wilmington             605
Durham                 538
Greensboro             485
Fayetteville           336
Asheville              243
Winston-Salem          225
Cary                   208
Name: City, dtype: int64

In [9]:
# No. of Accidents by Age
Biker_Age_df = bike_Pedestrain_crash_df.groupby("BikeAge")["BikeAge"].count().sort_values(ascending=False)
Biker_Age_df.head(20)

BikeAge
20    382
14    344
15    336
18    335
21    325
19    312
22    307
16    306
17    293
13    280
12    269
23    256
25    238
26    221
24    221
51    211
52    205
28    202
53    198
30    197
Name: BikeAge, dtype: int64

In [10]:
# No. of Accidents by Travel
Biker_travel_df = bike_Pedestrain_crash_df.groupby("BikeDir")["BikeDir"].count().sort_values(ascending=False)
Biker_travel_df.head(20)

BikeDir
With Traffic      7182
Facing Traffic    2964
Not Applicable    1360
Unknown            442
Name: BikeDir, dtype: int64

In [11]:
# No. of Accidents by Age-group
Biker_agegroup_df = bike_Pedestrain_crash_df.groupby("BikeAgeGrp")["BikeAgeGrp"].count().sort_values(ascending=False)
Biker_agegroup_df.head(20)

KeyError: 'BikeAgeGrp'

In [39]:
# Initial imports.
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression


In [40]:
!pip install imbalanced-learn==0.9.0

In [41]:
!pip install scikit-learn==1.0

  Using cached scikit_learn-1.0-cp39-cp39-win_amd64.whl (7.2 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
  Rolling back uninstall of scikit-learn
  Moving to c:\users\umar_\anaconda3\lib\site-packages\scikit_learn-1.0.2.dist-info\
   from C:\Users\umar_\anaconda3\Lib\site-packages\~cikit_learn-1.0.2.dist-info
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\__check_build\__init__.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-1yexvzki\__init__.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\__check_build\__pycache__\
   from C:\Users\umar_\anaconda3\Lib\site-packages\sklearn\__check_build\~_pycache__
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\__check_build\_check_build.cp39-win_amd64.pyd
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-1yexvzki\_check_build.cp39-win_amd64.pyd
  Movi

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\umar_\\anaconda3\\Lib\\site-packages\\sklearn\\.libs\\vcomp140.dll'
Consider using the `--user` option or check the permissions.



  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\decomposition\_nmf.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\decomposition\_nmf.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\decomposition\_online_lda_fast.cp39-win_amd64.pyd
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\decomposition\_online_lda_fast.cp39-win_amd64.pyd
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\decomposition\_pca.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\decomposition\_pca.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\decomposition\_sparse_pca.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\decomposition\_sparse_pca.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\decomposition\_truncated_svd.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\decomposition\_truncated_svd.py
  Moving to c:\users\umar_\anaconda3\lib\site-pack

In [42]:
X = bike_Pedestrain_crash_df.copy()
X = X.drop("CrashSevr", axis=1)
X = pd.get_dummies(X)
X.head(20)



   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\neighbors\_regression.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\neighbors\_unsupervised.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\neighbors\_unsupervised.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\neighbors\setup.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\neighbors\setup.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\neighbors\tests\__init__.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\neighbors\tests\__init__.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\neighbors\tests\__pycache__\__init__.cpython-39.pyc
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-rhwo35aw\neighbors\tests\__pycache__\__init__.cpython-39.pyc
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\neighbors\tests\__pycache__\test_ball_tree.cpython-39.pyc
   from C:\Users\umar_\A

CrashHour  CrashYear   Latitude  NumUnits  AmbulanceR_No  AmbulanceR_Yes  \
0          12       2010  35.231039         3              1               0   
1          13       2011  34.079405         2              0               1   
2          12       2012  35.975543         2              0               1   
3          11       2012  36.239883         2              1               0   
4          14       2012  34.684359         2              1               0   
5          20       2013  35.449133         2              1               0   
6          18       2014  36.062137         2              0               1   
7          22       2015  34.234440         2              0               1   
8          14       2016  34.271665         2              0               1   
9          18       2017  35.259753         2              0               1   
10         17       2016  35.558026         2              1               0   
11         23       2018  34.226472         2              0               1   
12         12       2018  35.323629         2              0               1   
13         16       2018  35.800453         2              0               1   
14         10       2018  34.884302         2              0               1   
15         12       2019  35.211377         2              1               0   
16         20       2013  36.097151         2              0               1   
17         17       2018  35.248185         2              0               1   
18          8       2010  35.594377         2              0               1   
19         20       2010  35.831351         2              1               0   

    BikeAge_0  BikeAge_1  BikeAge_10  BikeAge_11  ...  \
0           0          0           0           0  ...   
1           0          0           0           0  ...   
2           0          0           0           0  ...   
3           0          0           0           0  ...   
4           0          0           0           0  ...   
5           0          0           0           0  ...   
6           0          0           0           0  ...   
7           0          0           0           0  ...   
8           0          0           0           0  ...   
9           0          0           0           0  ...   
10          0          0           0           0  ...   
11          0          0           0           0  ...   
12          0          0           0           0  ...   
13          0          0           0           0  ...   
14          0          0           0           0  ...   
15          0          0           0           0  ...   
16          0          0           0           0  ...   
17          0          0           0           0  ...   
18          0          0           0           0  ...   
19          0          0           0           0  ...   

    TraffCntrl_Warning Sign  TraffCntrl_Yield Sign  Weather_Clear  \
0                         0                      0              0   
1                         0                      0              1   
2                         0                      0              1   
3                         0                      0              0   
4                         0                      0              1   
5                         0                      0              1   
6                         0                      0              1   
7                         0                      0              0   
8                         0                      0              0   
9                         0                      0              1   
10                        0                      0              1   
11                        0                      0              1   
12                        0                      0              1   
13                        0                      0              0   
14                        0                      0              1   
15                   

In [43]:
# Define the target set.
y = bike_Pedestrain_crash_df["CrashSevr"].ravel()
y[:20]

array(['O: No Injury', 'A: Suspected Serious Injury',
       'C: Possible Injury', 'C: Possible Injury', 'C: Possible Injury',
       'C: Possible Injury', 'B: Suspected Minor Injury',
       'B: Suspected Minor Injury', 'B: Suspected Minor Injury',
       'B: Suspected Minor Injury', 'O: No Injury', 'C: Possible Injury',
       'A: Suspected Serious Injury', 'B: Suspected Minor Injury',
       'O: No Injury', 'B: Suspected Minor Injury',
       'B: Suspected Minor Injury', 'B: Suspected Minor Injury',
       'B: Suspected Minor Injury', 'O: No Injury'], dtype=object)

In [74]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1, stratify=y)

In [75]:
classifier = LogisticRegression(solver='lbfgs',
   max_iter=200,
   random_state=1)

In [76]:
classifier.fit(X_train, y_train)

C:\Users\umar_\anaconda3\envs\PythonData\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(max_iter=200, random_state=1)

In [77]:
y_pred = classifier.predict(X_test)

In [78]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9705390023434884


In [49]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 155    0    2    0    4    0]
 [   3 1249    2    0    5    0]
 [   0    0 1164    1    8    0]
 [   9    8    5   44    2    1]
 [  10    0    9    5  286    0]
 [   1    0    0    1   12    1]]


In [50]:
report = classification_report(y_test, y_pred)
print(report)

                             precision    recall  f1-score   support

A: Suspected Serious Injury       0.87      0.96      0.91       161
  B: Suspected Minor Injury       0.99      0.99      0.99      1259
         C: Possible Injury       0.98      0.99      0.99      1173
                  K: Killed       0.86      0.64      0.73        69
               O: No Injury       0.90      0.92      0.91       310
             Unknown Injury       0.50      0.07      0.12        15

                   accuracy                           0.97      2987
                  macro avg       0.85      0.76      0.78      2987
               weighted avg       0.97      0.97      0.97      2987



In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  random_state=1, stratify=y)
X_train.shape

(8961, 968)

In [52]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [53]:
model.fit(X_train, y_train)

SVC(kernel='linear')

In [54]:
y_pred = model.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_pred,
   "Actual": y_test
}).reset_index(drop=True)
results.head()

Prediction                     Actual
0  B: Suspected Minor Injury  B: Suspected Minor Injury
1         C: Possible Injury         C: Possible Injury
2         C: Possible Injury         C: Possible Injury
3  B: Suspected Minor Injury  B: Suspected Minor Injury
4         C: Possible Injury         C: Possible Injury

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.995647807164379

In [56]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 160    0    1    0    0    0]
 [   1 1253    2    1    2    0]
 [   0    0 1169    0    4    0]
 [   0    0    1   68    0    0]
 [   0    0    0    0  310    0]
 [   0    0    0    0    1   14]]


In [57]:
report = classification_report(y_test, y_pred)
print(report)

                             precision    recall  f1-score   support

A: Suspected Serious Injury       0.99      0.99      0.99       161
  B: Suspected Minor Injury       1.00      1.00      1.00      1259
         C: Possible Injury       1.00      1.00      1.00      1173
                  K: Killed       0.99      0.99      0.99        69
               O: No Injury       0.98      1.00      0.99       310
             Unknown Injury       1.00      0.93      0.97        15

                   accuracy                           1.00      2987
                  macro avg       0.99      0.98      0.99      2987
               weighted avg       1.00      1.00      1.00      2987



In [84]:
#Desision tree
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [85]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8961, 968)
(2987, 968)
(8961,)
(2987,)


In [86]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [87]:
# Initial imports
import pandas as pd

from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [88]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [89]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)

In [115]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, predictions)
print(matrix) 

[[ 153    0    1    0    2    0]
 [   0 1239    3    0    7    0]
 [   0    0 1181    0   10    0]
 [   0    2    1   69    0    0]
 [   0    0    0    0  305    0]
 [   0    0    0    0    5    9]]


In [116]:
report = classification_report(y_test, predictions)
print(report)

                             precision    recall  f1-score   support

A: Suspected Serious Injury       1.00      0.98      0.99       156
  B: Suspected Minor Injury       1.00      0.99      1.00      1249
         C: Possible Injury       1.00      0.99      0.99      1191
                  K: Killed       1.00      0.96      0.98        72
               O: No Injury       0.93      1.00      0.96       305
             Unknown Injury       1.00      0.64      0.78        14

                   accuracy                           0.99      2987
                  macro avg       0.99      0.93      0.95      2987
               weighted avg       0.99      0.99      0.99      2987



In [117]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.9896216940073652

In [105]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [106]:
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.9896216940073652


In [82]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [95]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [96]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [97]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [98]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [99]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

In [101]:
cm

array([[ 153,    0,    1,    0,    2,    0],
       [   0, 1239,    3,    0,    7,    0],
       [   0,    0, 1181,    0,   10,    0],
       [   0,    2,    1,   69,    0,    0],
       [   0,    0,    0,    0,  305,    0],
       [   0,    0,    0,    0,    5,    9]], dtype=int64)

In [109]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.9896216940073652

In [110]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([7.86566727e-03, 6.83478357e-03, 9.80500527e-03, 8.91455616e-04,
       1.01917605e-02, 1.18290141e-02, 2.27516483e-06, 3.94976641e-06,
       3.08625208e-04, 4.04432470e-04, 4.92433288e-04, 4.55940390e-04,
       6.27514625e-04, 6.77339981e-04, 5.56768267e-04, 6.15655278e-04,
       6.42557533e-04, 4.99848573e-04, 1.31341357e-05, 6.51536914e-04,
       5.42298464e-04, 5.97052035e-04, 5.64437178e-04, 4.27956365e-04,
       4.72892094e-04, 4.81491171e-04, 4.70202675e-04, 4.16488846e-04,
       4.92480604e-04, 3.50560876e-05, 3.78352701e-04, 3.83270168e-04,
       3.41815025e-04, 3.90208157e-04, 3.46614413e-04, 4.84248675e-04,
       4.09899984e-04, 3.12987982e-04, 3.24716037e-04, 3.13292098e-04,
       5.34308852e-05, 3.62108738e-04, 3.47622429e-04, 2.76789344e-04,
       4.22227507e-04, 3.14666321e-04, 4.27708866e-04, 4.44019437e-04,
       3.85473718e-04, 4.48079230e-04, 5.15177521e-04, 1.53896742e-04,
       3.65204276e-04, 4.03020906e-04, 3.97328235e-04, 3.34320409e-04,
      

In [111]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.24930139814970897, 'BikeInjury_B: Suspected Minor Injury'),
 (0.2490864732757473, 'BikeInjury_C: Possible Injury'),
 (0.07495074071223587, 'BikeInjury_O: No Injury'),
 (0.05155886474314682, 'BikeInjury_A: Suspected Serious Injury'),
 (0.020275489381522897, 'BikeInjury_K: Killed'),
 (0.01182901407963739, 'AmbulanceR_Yes'),
 (0.010191760534872167, 'AmbulanceR_No'),
 (0.009805005270302383, 'Latitude'),
 (0.009306272502168627, 'BikeInjury_Unknown Injury'),
 (0.007865667272755289, 'CrashHour'),
 (0.0068347835701207185, 'CrashYear'),
 (0.0027027876668548963, 'BikeRace_Black'),
 (0.002526777225463787, 'BikeRace_White'),
 (0.002445003528381867, 'BikeDir_Facing Traffic'),
 (0.0021544815566054525, 'DrvrVehTyp_Passenger Car'),
 (0.002125475892361254, 'RdCharacte_Straight - Level'),
 (0.0021079485917018435, 'BikeDir_With Traffic'),
 (0.0020961607799559554, 'SpeedLimit_50 - 55  MPH'),
 (0.0020718648780896974, 'DrvrSex_Female'),
 (0.0020455802986006104, 'Developmen_Commercial'),
 (0.002004060806