In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [78]:
bike_Pedestrain_crash_df = pd.read_csv(R"C:\Users\umar_\OneDrive\Desktop\Capstone Project\Bikeride data.csv")
bike_Pedestrain_crash_df.head()

X          Y  OBJECTID_1 AmbulanceR BikeAge BikeAgeGrp  \
0 -80.878436  35.231039        3155         No       7       6-15   
1 -77.894637  34.079405        4236        Yes      41      40-49   
2 -78.973815  35.975543        5121        Yes      16      16-19   
3 -79.188513  34.684359        5631         No      46      40-49   
4 -78.686258  35.449133        6176         No      20      20-24   

                        BikeAlcDrg BikeAlcFlg         BikeDir  \
0  Yes-Drugs, impairment suspected         No    With Traffic   
1  Yes-Drugs, impairment suspected         No  Facing Traffic   
2  Yes-Drugs, impairment suspected         No    With Traffic   
3  Yes-Drugs, impairment suspected         No  Facing Traffic   
4  Yes-Drugs, impairment suspected         No    With Traffic   

                    BikeInjury  ... RuralUrban    SpeedLimit  \
0                 O: No Injury  ...      Urban  30 - 35  MPH   
1  A: Suspected Serious Injury  ...      Rural  40 - 45  MPH   
2           C: Possible Injury  ...      Urban  30 - 35  MPH   
3           C: Possible Injury  ...      Rural  30 - 35  MPH   
4           C: Possible Injury  ...      Rural  50 - 55  MPH   

                            TraffCntrl Weather Workzone OBJECTID Unnamed: 62  \
0                   No Control Present  Cloudy       No     3155         NaN   
1                   No Control Present   Clear       No     4236         NaN   
2                   No Control Present   Clear       No     5121         NaN   
3                   No Control Present   Clear       No     5631         NaN   
4  Double Yellow Line, No Passing Zone   Clear       No     6176         NaN   

  Unnamed: 63  Unnamed: 64  Unnamed: 65  
0         NaN          NaN          NaN  
1         NaN          NaN          NaN  
2         NaN          NaN          NaN  
3         NaN          NaN          NaN  
4         NaN          NaN          NaN  

[5 rows x 66 columns]

In [75]:
#Dropping unknown rows from Bike age group

bike_Pedestrain_crash_df.drop(bike_Pedestrain_crash_df[bike_Pedestrain_crash_df['BikeAgeGrp'] == 'Unknown'].index, inplace = True)
bike_Pedestrain_crash_df.drop(bike_Pedestrain_crash_df[bike_Pedestrain_crash_df['BikeAge'] == 'Unknown'].index, inplace = True)
bike_Pedestrain_crash_df.drop(bike_Pedestrain_crash_df[bike_Pedestrain_crash_df['DrvrAge'] == 'Unknown'].index, inplace = True)
bike_Pedestrain_crash_df.drop(bike_Pedestrain_crash_df[bike_Pedestrain_crash_df['DrvrAgeGrp'] == 'Unknown'].index, inplace = True)

In [80]:
bike_Pedestrain_crash_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11350 entries, 0 to 11349
Data columns (total 66 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   X            11350 non-null  float64
 1   Y            11350 non-null  float64
 2   OBJECTID_1   11350 non-null  int64  
 3   AmbulanceR   11350 non-null  object 
 4   BikeAge      11350 non-null  object 
 5   BikeAgeGrp   11350 non-null  object 
 6   BikeAlcDrg   11350 non-null  object 
 7   BikeAlcFlg   11350 non-null  object 
 8   BikeDir      11350 non-null  object 
 9   BikeInjury   11350 non-null  object 
 10  BikePos      11350 non-null  object 
 11  BikeRace     11350 non-null  object 
 12  BikeSex      11350 non-null  object 
 13  City         11350 non-null  object 
 14  County       11350 non-null  object 
 15  CrashAlcoh   11350 non-null  object 
 16  CrashDay     11350 non-null  object 
 17  CrashGrp     11350 non-null  object 
 18  CrashHour    11350 non-null  int64  
 19  Cras

In [81]:
# drop unneccasary columns
bike_Pedestrain_crash_df = bike_Pedestrain_crash_df.drop(['X', "Y","OBJECTID_1","BikeAlcFlg","CrashGrp","CrashID","NumBicsAin","NumBicsBin","NumBicsCin","NumBicsKil","NumBicsNoi","NumBicsTot","NumBicsUin","RuralUrban","OBJECTID",'Unnamed: 62',"Unnamed: 63", "Unnamed: 64","Unnamed: 65"], axis=1)

bike_Pedestrain_crash_df.head()

AmbulanceR BikeAge BikeAgeGrp                       BikeAlcDrg  \
0         No       7       6-15  Yes-Drugs, impairment suspected   
1        Yes      41      40-49  Yes-Drugs, impairment suspected   
2        Yes      16      16-19  Yes-Drugs, impairment suspected   
3         No      46      40-49  Yes-Drugs, impairment suspected   
4         No      20      20-24  Yes-Drugs, impairment suspected   

          BikeDir                   BikeInjury      BikePos         BikeRace  \
0    With Traffic                 O: No Injury  Travel Lane            Black   
1  Facing Traffic  A: Suspected Serious Injury  Travel Lane            White   
2    With Traffic           C: Possible Injury  Travel Lane            White   
3  Facing Traffic           C: Possible Injury  Travel Lane  Native American   
4    With Traffic           C: Possible Injury  Travel Lane         Hispanic   

  BikeSex                City  ... RdConditio  \
0    Male           Charlotte  ...        Dry   
1  Female  None - Rural Crash  ...        Dry   
2    Male              Durham  ...        Dry   
3    Male            Pembroke  ...        Dry   
4    Male  None - Rural Crash  ...        Dry   

                               RdConfig RdDefects           RdFeature  \
0                  Two-Way, Not Divided      None             Missing   
1  Two-Way, Divided, Unprotected Median      None    Driveway, Public   
2                  One-Way, Not Divided      None  No Special Feature   
3  Two-Way, Divided, Unprotected Median      None  No Special Feature   
4                  Two-Way, Not Divided      None  No Special Feature   

        RdSurface    Region    SpeedLimit  \
0  Smooth Asphalt  Piedmont  30 - 35  MPH   
1  Coarse Asphalt   Coastal  40 - 45  MPH   
2  Smooth Asphalt  Piedmont  30 - 35  MPH   
3  Smooth Asphalt   Coastal  30 - 35  MPH   
4  Smooth Asphalt   Coastal  50 - 55  MPH   

                            TraffCntrl  Weather Workzone  
0                   No Control Present   Cloudy       No  
1                   No Control Present    Clear       No  
2                   No Control Present    Clear       No  
3                   No Control Present    Clear       No  
4  Double Yellow Line, No Passing Zone    Clear       No  

[5 rows x 47 columns]

In [82]:
bike_Pedestrain_crash_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11350 entries, 0 to 11349
Data columns (total 47 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   AmbulanceR  11350 non-null  object 
 1   BikeAge     11350 non-null  object 
 2   BikeAgeGrp  11350 non-null  object 
 3   BikeAlcDrg  11350 non-null  object 
 4   BikeDir     11350 non-null  object 
 5   BikeInjury  11350 non-null  object 
 6   BikePos     11350 non-null  object 
 7   BikeRace    11350 non-null  object 
 8   BikeSex     11350 non-null  object 
 9   City        11350 non-null  object 
 10  County      11350 non-null  object 
 11  CrashAlcoh  11350 non-null  object 
 12  CrashDay    11350 non-null  object 
 13  CrashHour   11350 non-null  int64  
 14  CrashLoc    11350 non-null  object 
 15  CrashMonth  11350 non-null  object 
 16  CrashSevr   11350 non-null  object 
 17  CrashType   11350 non-null  object 
 18  CrashYear   11350 non-null  int64  
 19  Developmen  11350 non-nul

In [83]:
# Initial imports.
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression


In [84]:
!pip install imbalanced-learn==0.9.0

In [85]:
!pip install scikit-learn==1.0

  Using cached scikit_learn-1.0-cp39-cp39-win_amd64.whl (7.2 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
  Rolling back uninstall of scikit-learn
  Moving to c:\users\umar_\anaconda3\lib\site-packages\scikit_learn-1.0.2.dist-info\
   from C:\Users\umar_\anaconda3\Lib\site-packages\~cikit_learn-1.0.2.dist-info
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\__check_build\__init__.py
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-mnvw67vm\__init__.py
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\__check_build\__pycache__\
   from C:\Users\umar_\anaconda3\Lib\site-packages\sklearn\__check_build\~_pycache__
  Moving to c:\users\umar_\anaconda3\lib\site-packages\sklearn\__check_build\_check_build.cp39-win_amd64.pyd
   from C:\Users\umar_\AppData\Local\Temp\pip-uninstall-mnvw67vm\_check_build.cp39-win_amd64.pyd
  Movi

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\umar_\\anaconda3\\Lib\\site-packages\\sklearn\\.libs\\vcomp140.dll'
Consider using the `--user` option or check the permissions.



In [86]:
X = bike_Pedestrain_crash_df.copy()
X = X.drop("CrashSevr", axis=1)
X = pd.get_dummies(X)
X.head(20)

CrashHour  CrashYear   Latitude  Longitude  NumUnits  AmbulanceR_No  \
0          12       2010  35.231039 -80.878436         3              1   
1          13       2011  34.079405 -77.894637         2              0   
2          12       2012  35.975543 -78.973815         2              0   
3          14       2012  34.684359 -79.188513         2              1   
4          20       2013  35.449133 -78.686258         2              1   
5          18       2014  36.062137 -79.815604         2              0   
6          22       2015  34.234440 -77.888058         2              0   
7          14       2016  34.271665 -77.927033         2              0   
8          18       2017  35.259753 -81.216746         2              0   
9          17       2016  35.558026 -77.457629         2              1   
10         23       2018  34.226472 -77.931580         2              0   
11         10       2018  34.884302 -76.912357         2              0   
12         12       2019  35.211377 -80.692467         2              1   
13         17       2018  35.248185 -81.612973         2              0   
14         20       2010  35.831351 -77.416470         2              1   
15         18       2010  34.231652 -78.056550         2              0   
16         14       2010  36.050402 -79.798069         2              0   
17         16       2010  35.474798 -80.609790         2              0   
18          6       2010  34.674170 -79.185474         2              0   
19         18       2010  35.587905 -77.230832         2              1   

    AmbulanceR_Yes  BikeAge_0  BikeAge_1  BikeAge_10  ...  \
0                0          0          0           0  ...   
1                1          0          0           0  ...   
2                1          0          0           0  ...   
3                0          0          0           0  ...   
4                0          0          0           0  ...   
5                1          0          0           0  ...   
6                1          0          0           0  ...   
7                1          0          0           0  ...   
8                1          0          0           0  ...   
9                0          0          0           0  ...   
10               1          0          0           0  ...   
11               1          0          0           0  ...   
12               0          0          0           0  ...   
13               1          0          0           0  ...   
14               0          0          0           0  ...   
15               1          0          0           0  ...   
16               1          0          0           0  ...   
17               1          0          0           0  ...   
18               1          0          0           0  ...   
19               0          0          0           0  ...   

    TraffCntrl_Warning Sign  TraffCntrl_Yield Sign  Weather_Clear  \
0                         0                      0              0   
1                         0                      0              1   
2                         0                      0              1   
3                         0                      0              1   
4                         0                      0              1   
5                         0                      0              1   
6                         0                      0              0   
7                         0                      0              0   
8                         0                      0              1   
9                         0                      0              1   
10                        0                      0              1   
11                        0                      0              1   
12                        0                      0              1   
13                        0                      0              1   
14                        0                      0              1   
15                        0               

In [87]:
# Define the target set.
y = bike_Pedestrain_crash_df["CrashSevr"].ravel()
y[:20]

array(['O: No Injury', 'A: Suspected Serious Injury',
       'C: Possible Injury', 'C: Possible Injury', 'C: Possible Injury',
       'B: Suspected Minor Injury', 'B: Suspected Minor Injury',
       'B: Suspected Minor Injury', 'B: Suspected Minor Injury',
       'O: No Injury', 'C: Possible Injury', 'O: No Injury',
       'B: Suspected Minor Injury', 'B: Suspected Minor Injury',
       'O: No Injury', 'B: Suspected Minor Injury',
       'B: Suspected Minor Injury', 'C: Possible Injury',
       'C: Possible Injury', 'O: No Injury'], dtype=object)

In [88]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1, stratify=y)

In [89]:
classifier = LogisticRegression(solver='lbfgs',
   max_iter=200,
   random_state=1)

In [90]:
classifier.fit(X_train, y_train)

C:\Users\umar_\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=200, random_state=1)

In [91]:
y_pred = classifier.predict(X_train)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_pred))

0.9774436090225563


In [92]:
y_pred = classifier.predict(X_test)


In [93]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9735729386892178


In [94]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 137    1    3    0    7    1]
 [   3 1159    0    1    7    0]
 [   1    1 1099    1   12    0]
 [   1    7    2   51    1    1]
 [   1    1    7    0  316    1]
 [   1    1    1    1   11    1]]


In [95]:
report = classification_report(y_test, y_pred)
print(report)

                             precision    recall  f1-score   support

A: Suspected Serious Injury       0.95      0.92      0.94       149
  B: Suspected Minor Injury       0.99      0.99      0.99      1170
         C: Possible Injury       0.99      0.99      0.99      1114
                  K: Killed       0.94      0.81      0.87        63
               O: No Injury       0.89      0.97      0.93       326
             Unknown Injury       0.25      0.06      0.10        16

                   accuracy                           0.97      2838
                  macro avg       0.84      0.79      0.80      2838
               weighted avg       0.97      0.97      0.97      2838



In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  random_state=1, stratify=y)
X_train.shape

(8512, 724)

In [97]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [98]:
model.fit(X_train, y_train)

SVC(kernel='linear')

In [99]:
y_pred = model.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_pred,
   "Actual": y_test
}).reset_index(drop=True)
results.head()

Prediction                     Actual
0         C: Possible Injury         C: Possible Injury
1  B: Suspected Minor Injury  B: Suspected Minor Injury
2         C: Possible Injury         C: Possible Injury
3         C: Possible Injury         C: Possible Injury
4         C: Possible Injury         C: Possible Injury

In [100]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9961240310077519

In [101]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 148    0    0    0    1    0]
 [   1 1168    0    0    1    0]
 [   0    1 1109    0    4    0]
 [   0    1    0   62    0    0]
 [   0    1    0    0  324    1]
 [   0    0    0    0    0   16]]


In [102]:
report = classification_report(y_test, y_pred)
print(report)

                             precision    recall  f1-score   support

A: Suspected Serious Injury       0.99      0.99      0.99       149
  B: Suspected Minor Injury       1.00      1.00      1.00      1170
         C: Possible Injury       1.00      1.00      1.00      1114
                  K: Killed       1.00      0.98      0.99        63
               O: No Injury       0.98      0.99      0.99       326
             Unknown Injury       0.94      1.00      0.97        16

                   accuracy                           1.00      2838
                  macro avg       0.99      0.99      0.99      2838
               weighted avg       1.00      1.00      1.00      2838



In [103]:
#Desision tree
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [104]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8512, 724)
(2838, 724)
(8512,)
(2838,)


In [105]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [106]:
# Initial imports
import pandas as pd

from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [107]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [108]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)

In [109]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, predictions)
print(matrix) 

[[ 149    0    0    0    0    0]
 [   1 1136    0    3    0    0]
 [   1    1 1147    0    1    0]
 [   0    0    0   54    0    0]
 [   0    3    5    0  317    0]
 [   0    0    0    0    1   19]]


In [110]:
report = classification_report(y_test, predictions)
print(report)

                             precision    recall  f1-score   support

A: Suspected Serious Injury       0.99      1.00      0.99       149
  B: Suspected Minor Injury       1.00      1.00      1.00      1140
         C: Possible Injury       1.00      1.00      1.00      1150
                  K: Killed       0.95      1.00      0.97        54
               O: No Injury       0.99      0.98      0.98       325
             Unknown Injury       1.00      0.95      0.97        20

                   accuracy                           0.99      2838
                  macro avg       0.99      0.99      0.99      2838
               weighted avg       0.99      0.99      0.99      2838



In [111]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.9943622269203665

In [112]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [113]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [114]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [115]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [116]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [117]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

In [118]:
cm

array([[ 168,    0,    0,    0,    3,    0],
       [   0, 1164,    1,    0,    1,    0],
       [   0,    0, 1113,    0,    7,    0],
       [   0,    5,    2,   63,    0,    0],
       [   0,    0,    0,    0,  300,    0],
       [   0,    0,    0,    0,    6,    5]], dtype=int64)

In [119]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.9911909795630726

In [120]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([7.65382721e-03, 6.48949732e-03, 9.41584358e-03, 9.72708806e-03,
       1.00914074e-03, 1.22980211e-02, 1.08608406e-02, 0.00000000e+00,
       1.15300805e-05, 3.48908062e-04, 4.00924311e-04, 5.44211837e-04,
       4.21964370e-04, 4.48143587e-04, 5.14972210e-04, 4.70839575e-04,
       5.56471554e-04, 4.87239654e-04, 4.46817625e-04, 8.39498072e-06,
       6.23571080e-04, 6.02063435e-04, 5.54608588e-04, 4.02100218e-04,
       3.93443035e-04, 4.03865167e-04, 3.72398626e-04, 4.01607154e-04,
       3.26283824e-04, 3.52034857e-04, 5.06089219e-05, 4.10738286e-04,
       2.80721996e-04, 3.25980679e-04, 2.73851896e-04, 3.03735339e-04,
       3.21036414e-04, 3.68160955e-04, 3.61995587e-04, 2.10399815e-04,
       2.96331093e-04, 6.47249272e-05, 2.48427373e-04, 3.40751856e-04,
       2.85852800e-04, 4.56572205e-04, 3.95901250e-04, 3.83499979e-04,
       3.70782413e-04, 4.41953704e-04, 4.11241292e-04, 4.55667711e-04,
       1.19420504e-04, 2.84365181e-04, 3.38671888e-04, 3.68962338e-04,
      

In [121]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.2628040425869049, 'BikeInjury_C: Possible Injury'),
 (0.21962000578128443, 'BikeInjury_B: Suspected Minor Injury'),
 (0.07819304584288422, 'BikeInjury_O: No Injury'),
 (0.04816659713234519, 'BikeInjury_A: Suspected Serious Injury'),
 (0.01984921451986307, 'BikeInjury_K: Killed'),
 (0.013790473479429794, 'BikeInjury_Unknown Injury'),
 (0.012298021117312471, 'AmbulanceR_No'),
 (0.010860840607300765, 'AmbulanceR_Yes'),
 (0.009727088064034235, 'Longitude'),
 (0.009415843575063212, 'Latitude'),
 (0.007653827205724165, 'CrashHour'),
 (0.00648949731526279, 'CrashYear'),
 (0.003887794345497586, 'BikeRace_Unknown/Missing'),
 (0.003226430941138887, 'BikeAgeGrp_Unknown'),
 (0.0030517799388452014, 'BikeDir_Facing Traffic'),
 (0.0027228075477218347, 'BikeSex_Unknown'),
 (0.002674002557106797, 'BikeRace_Black'),
 (0.002368675864356283, 'BikeRace_White'),
 (0.0021223235950035674, 'BikeDir_With Traffic'),
 (0.0020927004107246377, 'DrvrInjury_O: No Injury'),
 (0.002086213878186684, 'BikeAge_999'),
